export const SHOW_SUCCESS_MESSAGE = 'APP/SHOW_SUCCESS_MESSAGE'
export const SHOW_ERROR_MESSAGE = 'APP/SHOW_ERROR_MESSAGE'
export const CLEAR_MESSAGE = 'APP/CLEAR_MESSAGE'

export const GET_TASK = 'TASK/GET_TASK'
export const GET_ALL_TASKS = 'TASK/GET_ALL_TASKS'
export const SET_TASK_ACCEPTED = 'TASK/SET_TASK_ACCEPTED'
export const SET_TASK_COMPLETED = 'TASK/SET_TASK_COMPLETED'
export const GET_TASK_HISTORY = 'TASK/GET_TASK_HISTORY'

export const GET_ALL_PHARMACIES = 'ADDRESSES/GET_ALL_PHARMACIES'

export const SET_USER = 'USER/SET_USER'
export const CLEAR_USER = 'USER/CLEAR_USER'
