export const THEME = {
  MAIN_COLOR: '#303f9f',
  BACKGROUND_COLOR: '#f8f8f8',
  WHITE_COLOR: '#fff',
  SUCCESS_COLOR: '#28a745',
  PRIMARY_COLOR: '#037bff',
  DANGER_COLOR: '#dc3545',
  TABLE_ROWS_MARGIN: 6,
  MARGIN_BOTTOM: 20,
  PADDING: 15,
}
