export const THEME = {
  // COLORS:
  BACKGROUND_COLOR: '#F7F8FA',
  MAIN_COLOR: '#60D67A',
  WHITE_COLOR: '#FFFFFF',
  FONT_COLOR: '#3C3E3F',
  LABEL_FONT_COLOR: '#B8BFC9',
  ICON_COLOR: '#9399A1',

  // SIZES:
  FONT_SIZE: '14px'
}
