export const THEME = {
  // COLORS:
  BACKGROUND_COLOR: '#F7F8FA',
  GREEN_COLOR: '#60D67A',
  BLUE_COLOR: '#37BBEB',
  WHITE_COLOR: '#FFFFFF',
  GREY_COLOR: '#9399A1',
  LIGHT_GREY_COLOR: '#B8BFC9',
  FONT_COLOR: '#3C3E3F',
  LABEL_FONT_COLOR: '#B8BFC9',
  LOGO_TEXT_COLOR: '#4D5054',

  // SIZES:
  FONT_SIZE: '14px'
}
