export const SHOW_LOADER = 'APP/SHOW_LOADER'
export const HIDE_LOADER = 'APP/HIDE_LOADER'
export const SHOW_LOADER_WITH_MESSAGE = 'APP/SHOW_LOADER_WITH_MESSAGE'
export const HIDE_LOADER_WITH_MESSAGE = 'APP/HIDE_LOADER_WITH_MESSAGE'

export const GET_TASK = 'TASK/GET_TASK'
export const GET_ALL_TASKS = 'TASK/GET_ALL_TASKS'
export const SET_TASK_STATUS = 'TASK/SET_TASK_STATUS'
